// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAsLQDwHSJZOBNxLiXav2wugq8VkXfiGA',
    appId: '1:228111135092:web:d121dffa95ab2bcf21bc21',
    messagingSenderId: '228111135092',
    projectId: 'fl-fire-test-9f13c',
    authDomain: 'fl-fire-test-9f13c.firebaseapp.com',
    storageBucket: 'fl-fire-test-9f13c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGh1cQLVu4vbGY3cBytbRha94jYQRgYBM',
    appId: '1:228111135092:android:d363a5f46182981821bc21',
    messagingSenderId: '228111135092',
    projectId: 'fl-fire-test-9f13c',
    storageBucket: 'fl-fire-test-9f13c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChxMUR10B_K7VURX_eZ4XoLQJs1I1DqYo',
    appId: '1:228111135092:ios:dbd2cd3c9456ca3121bc21',
    messagingSenderId: '228111135092',
    projectId: 'fl-fire-test-9f13c',
    storageBucket: 'fl-fire-test-9f13c.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChxMUR10B_K7VURX_eZ4XoLQJs1I1DqYo',
    appId: '1:228111135092:ios:11938a0be4c46cb321bc21',
    messagingSenderId: '228111135092',
    projectId: 'fl-fire-test-9f13c',
    storageBucket: 'fl-fire-test-9f13c.appspot.com',
    iosBundleId: 'com.example.chatApplication.RunnerTests',
  );
}
